language: C
addons:
    apt:
        packages:
        - libgmp-dev
        - libmpfr-dev
install: bash scripts/build_cross_compiler.sh
cache:
    apt: true
    directories:
        - compiler/
script: make
