language: C
addons:
    apt:
        packages:
        - libgmp-dev
        - libmpfr-dev
cache:
    apt: true
    #directories:
    #    - compiler/
#install: bash scripts/build_cross_compiler.sh
script:
    - make run-tests
